"""from .meeting_room import MeetingRoom

Revision ID: 5ab49df1b0ef
Revises: e7e8c1b1d750
Create Date: 2024-09-04 23:33:17.926198

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5ab49df1b0ef'
down_revision = 'e7e8c1b1d750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_reserve', sa.DateTime(), nullable=True),
    sa.Column('to_reserve', sa.DateTime(), nullable=True),
    sa.Column('meetingroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetingroom_id'], ['meetingroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
