"""Reservation

Revision ID: 06bc908bef2b
Revises: 5ab49df1b0ef
Create Date: 2024-09-10 13:29:29.751699

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '06bc908bef2b'
down_revision = '5ab49df1b0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
